@ECHO OFF
echo Creating virtual environment...
py -m venv venv >NUL
echo Installing requirements for the virtual environment...
venv\Scripts\python.exe -m pip install -r requirements.txt >NUL
echo Launching Flask server...
venv\Scripts\python.exe -m flask run
CALL venv\Scripts\activate.bat